version: 2
seeds:
  - name: customers
    description: Customer description, one record per customer # add a description to the table
    columns:
      - name: customer_id
        description: Primary key # add a description to column customer_id
        tests:
          - unique
          - not_null
      - name: first_name
        description: first name of user

  - name: orders
    description: Description of customer orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: [ 'placed', 'shipped', 'completed', 'return_pending', 'returned' ]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null


  - name: customer_order_history
    description: >
      In this table, we describe the purchase history of all customers. We will show the date of the first and the last
      purchase of the customer. We will also show the total order of a customer
    columns:
      - name: customer_id
        description: the id of the customer
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: first_order_date
        description: The date of the first purcharse
      - name: most_recent_order_date
        description: The date of the last purcharse
      - name: number_of_orders
        description: NULL when a customer has not yet placed an order.